export const books = [
  // Classic Fiction
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic Fiction",
    year: 1925,
    rating: 4.2,
    available: true,
    cover: "to be filled",
    description: "A story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, set in the Jazz Age on Long Island.",
    pages: 180,
    publisher: "Scribner",
    isbn: "978-0-7432-7356-5"
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic Fiction",
    year: 1960,
    rating: 4.8,
    available: true,
    cover: "to be filled",
    description: "The story of racial injustice and the loss of innocence in the American South, seen through the eyes of young Scout Finch.",
    pages: 281,
    publisher: "J. B. Lippincott & Co.",
    isbn: "978-0-06-112008-4"
  },
  {
    id: 3,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Classic Fiction",
    year: 1813,
    rating: 4.6,
    available: true,
    cover: "to be filled",
    description: "The story of Elizabeth Bennet and her complex relationship with the proud Mr. Darcy in 19th century England.",
    pages: 432,
    publisher: "T. Egerton",
    isbn: "978-0-14-143951-8"
  },

  // Fantasy
  {
    id: 4,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1937,
    rating: 4.8,
    available: true,
    cover: "to be filled",
    description: "Bilbo Baggins is swept into an epic quest to reclaim a treasure guarded by the dragon Smaug.",
    pages: 310,
    publisher: "George Allen & Unwin",
    isbn: "978-0-618-00221-3"
  },
  {
    id: 5,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: 1954,
    rating: 4.9,
    available: true,
    cover: "to be filled",
    description: "Frodo Baggins and his fellowship embark on a perilous quest to destroy the One Ring and defeat the Dark Lord Sauron.",
    pages: 1178,
    publisher: "George Allen & Unwin",
    isbn: "978-0-618-64015-7"
  },
  {
    id: 6,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    genre: "Fantasy",
    year: 1996,
    rating: 4.7,
    available: false,
    cover: "to be filled",
    description: "Noble families fight for control of the Iron Throne while an ancient enemy returns after a long summer.",
    pages: 694,
    publisher: "Bantam Books",
    isbn: "978-0-553-57340-3"
  },
  {
    id: 7,
    title: "The Name of the Wind",
    author: "Patrick Rothfuss",
    genre: "Fantasy",
    year: 2007,
    rating: 4.6,
    available: true,
    cover: "to be filled",
    description: "The legend of Kvothe, a magically gifted young man who grows from an orphan to the most notorious wizard his world has ever seen.",
    pages: 662,
    publisher: "DAW Books",
    isbn: "978-0-7564-0407-9"
  },

  // Dystopian
  {
    id: 8,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: 1949,
    rating: 4.7,
    available: false,
    cover: "to be filled",
    description: "A chilling dystopia of a totalitarian society where Big Brother watches your every move.",
    pages: 328,
    publisher: "Secker & Warburg",
    isbn: "978-0-452-28423-4"
  },
  {
    id: 9,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    year: 1932,
    rating: 4.3,
    available: true,
    cover: "to be filled",
    description: "A futuristic society where humans are engineered for specific roles and happiness is enforced through drugs.",
    pages: 311,
    publisher: "Chatto & Windus",
    isbn: "978-0-06-085052-4"
  },
  {
    id: 10,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    year: 2008,
    rating: 4.7,
    available: true,
    cover: "to be filled",
    description: "In a dystopian future, teenager Katniss Everdeen volunteers to take her sister's place in a televised death tournament.",
    pages: 374,
    publisher: "Scholastic Press",
    isbn: "978-0-439-02348-1"
  },
  {
    id: 11,
    title: "Divergent",
    author: "Veronica Roth",
    genre: "Dystopian",
    year: 2011,
    rating: 4.3,
    available: true,
    cover: "to be filled",
    description: "In a future Chicago divided into factions, Tris Prior discovers she is Divergent and uncovers a conspiracy threatening her world.",
    pages: 487,
    publisher: "Katherine Tegen Books",
    isbn: "978-0-06-202402-2"
  },

  // Adventure
  {
    id: 12,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    year: 1988,
    rating: 4.5,
    available: false,
    cover: "to be filled",
    description: "A young shepherd embarks on a journey to find treasure and discovers the true meaning of his destiny.",
    pages: 208,
    publisher: "HarperOne",
    isbn: "978-0-06-231609-7"
  },
  {
    id: 13,
    title: "The Maze Runner",
    author: "James Dashner",
    genre: "Adventure",
    year: 2009,
    rating: 4.4,
    available: true,
    cover: "to be filled",
    description: "Thomas wakes up in a mysterious maze with no memory of his past, and must find a way out with a group of other trapped teens.",
    pages: 374,
    publisher: "Delacorte Press",
    isbn: "978-0-385-73794-4"
  },
  {
    id: 14,
    title: "Ready Player One",
    author: "Ernest Cline",
    genre: "Adventure",
    year: 2011,
    rating: 4.5,
    available: true,
    cover: "to be filled",
    description: "In a future where most of humanity escapes reality in a virtual world, a teenager hunts for a hidden easter egg that will make him rich.",
    pages: 374,
    publisher: "Crown Publishers",
    isbn: "978-0-307-88743-6"
  },

  // Romance
  {
    id: 15,
    title: "The Notebook",
    author: "Nicholas Sparks",
    genre: "Romance",
    year: 1996,
    rating: 4.4,
    available: true,
    cover: "to be filled",
    description: "A poor young man falls in love with a rich girl in 1940s North Carolina, and their story is read from a notebook years later.",
    pages: 214,
    publisher: "Warner Books",
    isbn: "978-0-446-52318-2"
  },
  {
    id: 16,
    title: "Outlander",
    author: "Diana Gabaldon",
    genre: "Romance",
    year: 1991,
    rating: 4.6,
    available: false,
    cover: "to be filled",
    description: "A WWII nurse is mysteriously transported back to 18th century Scotland where she falls in love with a Highland warrior.",
    pages: 850,
    publisher: "Delacorte Press",
    isbn: "978-0-440-21256-1"
  },

  // Coming of Age
  {
    id: 17,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Coming of Age",
    year: 1951,
    rating: 4.0,
    available: true,
    cover: "to be filled",
    description: "Holden Caulfield narrates his experiences in New York City after being expelled from prep school.",
    pages: 277,
    publisher: "Little, Brown and Company",
    isbn: "978-0-316-76948-0"
  },
  {
    id: 18,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Coming of Age",
    year: 1997,
    rating: 4.9,
    available: false,
    cover: "to be filled",
    description: "A young boy discovers he is a wizard and begins his journey at Hogwarts School of Witchcraft and Wizardry.",
    pages: 309,
    publisher: "Bloomsbury",
    isbn: "978-0-439-70818-8"
  },
  {
    id: 19,
    title: "The Perks of Being a Wallflower",
    author: "Stephen Chbosky",
    genre: "Coming of Age",
    year: 1999,
    rating: 4.5,
    available: true,
    cover: "to be filled",
    description: "Charlie navigates his freshman year of high school through letters, dealing with trauma, friendship, and first love.",
    pages: 213,
    publisher: "Pocket Books",
    isbn: "978-1-4516-2133-1"
  }
];

export const genres = ["All", "Classic Fiction", "Fantasy", "Dystopian", "Adventure", "Romance", "Coming of Age"];
